/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mihome.education_hibernate.one_table;

import com.mihome.education_hibernate.one_table.entity.Employee;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class AddEmployee {

    public static void main(String[] args) {

        SessionFactory sessionFactory = new Configuration()
                .configure("hibernate.cfg.xml")
                .addAnnotatedClass(Employee.class)
                .buildSessionFactory();

        Employee emp = new Employee("Gogol", "Mogol", "Poliana", 530);
        try {
            Session session = sessionFactory.getCurrentSession();
            session.beginTransaction();

//            session.save(emp);

            session.persist(emp);

            session.getTransaction().commit();
            
        } finally {
            sessionFactory.close();
        }

    }
}
